remote_theme: daattali/beautiful-jekyll


title: AttaliTech

author: AttaliTech Ltd

navbar-links:
  Services: "/#services"
  About Us: "/#aboutus"
  Clients: "/#clients"
  Open-Source: "/#portfolio"
  Contact Us: "/contact"

title-img: /assets/img/attalitech-logo-light.png

site-css: "/assets/css/attalitech.css"

keywords: "r shiny,shiny developer,shiny consultant,r consultant,shiny apps"

mobile-theme-col: "#0085A1"
navbar-col: "#05172d"
navbar-text-col: "#fff"
navbar-border-col: "#05172d"

social-network-links:
  email: "info@attalitech.com"
  github: daattali
  twitter: daattali
  calendly: "attalitech/meeting"
  youtube: "@daattali?sub_confirmation=1"
  patreon: DeanAttali
  telephone: +16042274469

url-pretty: "AttaliTech.com"

footer-img: "/assets/img/footer-bg.png"

gtag: "G-Y80XD5LXBY"

timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      footer-extra: custom_footer.html
      nav-short: true
      share-description: "AttaliTech provides world-class R/Shiny consulting and development services. We develop enterprise Shiny apps, perform code audits, build professional R packages, and more. Led by renowned expert Dean Attali."
      share-img: "/assets/img/attalitech.png"

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md


plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
